#+title: Premières Analyses des Données de Séquençage
#+author: Samuel BARRETO
#+date: \today
#+latex_header: \usepackage[frenchle]{babel}
#+latex_header: \usepackage{biolinum}
#+latex_header: \usepackage[euler-digits]{eulervm}
#+latex_header: \renewcommand{\footnotesize}{\small}
#+language: fr
#+options: toc:nil

* Qualité des données
** qualité du séquençage 
#+name: qualité des séquences
#+BEGIN_LaTeX
\begin{marginfigure}
  \includegraphics[width=\linewidth]{../per_base_quality_fastqc_untrimmed.png}
  \caption{Qualité des séquences \emph{avant} d'être trimmées et filtrées
      sur la qualité}
\end{marginfigure}

\begin{marginfigure}
  \includegraphics[width=\linewidth]{../per_base_quality_fastqc_trimmed.png}
  \caption{Qualité des séquences \emph{après} avoir été trimmées et filtrées
      sur la qualité}
\end{marginfigure}
#+END_LaTeX

Globalement la plupart des séquences était de bonne qualité. Sur les $192$
envoyées à séquencer, $170$ ont été retenues pour l'analyse, soit $89$ %.

Étant donnée la faible qualité des bases en début et en fin de séquence, elles
ont été tronquées. Le score $28$ semblait le seuil naturel de qualité. De plus,
toutes les séquences qui avaient une longueur inférieure à $620$ étaient
généralement mal alignées. Elles ont été éliminées de l'analyse. 

Il reste au final $83$ séquence de Strong et $87$ séquences de Weak. 

** Présence de contaminations ?
*** dans la manip Strong

#+attr_latex: :font \small
|           | *SNP weak* | *SNP strong* |
|-----------+------------+--------------|
| <c>       | <c>        | <c>          |
| pS60-1073 | 22         |              |
| pS83-1073 | 21         |              |
| pS91-1073 | 22         |              |
| pS92-1073 | 22         |              |
| pW6-1073  |            | 10           |

Toutes ces séquences ont été ``rebasculées'' dans la catégorie qui leur
convient. 
** Observations générales

#+BEGIN_LaTeX
\begin{margintable}
  \small
  \input{../observations.tex}
\end{margintable}
#+END_LaTeX

Il y a $1236$ SNP générés par l'exogène Strong, et $1192$ SNP générés par l'exogène
Weak. \\
#+BEGIN_LaTeX
\begin{center}
  {\sffamily \input{../count_by_muttype.tex}}
\end{center}
#+END_LaTeX

\newpage
* Distribution des SNPs
** Distribution globale
#+BEGIN_LaTeX
\begin{figure*}[h]
  \centering
  \includegraphics[width=\linewidth]{../snp_distribution.pdf}
  \caption{La distibution des SNPs, sans tenir compte de la qualité de la
    mutation. La couleur représente le mutant d'origine.}
  \label{fig:snpdistrib}
\end{figure*}
#+END_LaTeX

Ce graphe représente la distribution des SNPs sur la séquence de référence. Les
barres vertes représentent les SNP des gènes synthétiques Strong, les rouges
celles des Weak. 

Première observation : il y a plus de SNP dans les régions 5' que 3'. Artefact
de séquençage ? Quand on regarde la qualité du /base call/ et les spectrogrammes
associés, il ne semble pas. 

Deuxième observation : les gènes synthétiques Strong génèrent /légèrement/ plus
de SNPs en 3' que les Weak. À tester, pas certain que ce soit significatif.

\newthought{Conclusion} : il y a plus de substitutions dans les régions 3' que 5',
sur la fin de la conversion tract. Où se fait le switch ? 

#+BEGIN_LaTeX
\marginnote{ À noter qu'on n'a pas de SNP après la position 691, alors que la
  séquence de référence mesure $734$bp. C'est dû au \emph{trimming} des
  séquences. On perd l'information des premiers SNP. }
#+END_LaTeX

\newpage
** Distribution de la qualité des mutation 

#+BEGIN_LaTeX
\begin{figure*}[h]
  \centering
  \includegraphics[width=\linewidth]{../mutant_snp_distribution.pdf}
  \caption{\textbf{Distribution des SNP par position sur la séquence de référence.} \\
    On retrouve bien les positions des polymorphismes ``artificiels'', toutes
    les $30$ paires de bases. En vert les mutations \emph{strong} et en rouge
    les mutations \emph{weak}. Les mutants Strong montrent quasiment
    exclusivement des substitutions \emph{strong}. Les mutants Weak montrent
    aussi exclusivement des substitutions \emph{weak}. }
  \label{fig:mutsnpdistrib}
\end{figure*}
#+END_LaTeX

En haut, la distribution des SNP générés par les gènes synthétiques de type
Strong ; en bas, celle des gènes synthétiques de type Weak. Les barres rouges 
représentent les substitutions vers $GC$, /strong/ ; les barres vertes les
substitutions vers $AT$, /weak/, les quelques barres bleues --- il y en a trois
--- représentent les mutations spontanées $WW$. 

Lorsque le gène synthétique est de type Strong, les substitutions occasionnées
sont --- quasiment --- exclusivement de type /strong/ ; idem pour les gènes
synthétiques Weak. 

\clearpage
* Distribution de la position de basculement
** Basculement terminal global
#+BEGIN_LaTeX
\begin{figure*}
  \centering
  \includegraphics[width=\linewidth]{../switch_distrib.pdf}
  \caption{\textbf{Position des switch, indifféremment de la qualité de la
      substition ou du mutant}. \\
    Il y a des disparités dans la distribution des positions de basculement. Il
    y a beaucoup de basculement dès le début, moins vers la fin. Il semble y
    avoir une sorte de \emph{coldspot} local, autour de $500$bp et $200$bp sur
    la séquence de référence. }
\end{figure*}
#+END_LaTeX

Ce graphe représente la distribution du dernier SNP par mutant : autrement dit,
la position de basculement. Il y a une très forte hétérogénéité. Peut-on parler
de coldspot / hotspot local ?

On ne voit pas de divergence très nette entre l'haplotype Weak et l'haplotype
Strong, mis à part peut-être le pic dans les premiers SNP, plus fort pour le
Weak\ldots

\newpage

