#!/usr/bin/env python
"""
============
ab1_to_fastq
============

Un module pour convertir le fichier .ab1 en fichier fastq.
"""

from __future__ import print_function
import sys
from Bio import SeqIO


for line in sys.stdin:
    assert line.rstrip().endswith(".ab1"), "not an ab1 file"
    with open(line.rstrip(), "rb") as ab1_file:
        ab1_record = SeqIO.read(ab1_file, "abi")
        print(ab1_record.format("fastq"))
