#!/usr/local/bin/bash
# quand dans le dossier ./scripts
cd ../data/

if [ -f untrimmed.fastq ]; then # si le dossier tmp existe
    rm untrimmed.fastq
    cat fastq/*.fastq > untrimmed.fastq
else
    cat fastq/*.fastq > untrimmed.fastq
fi

fastqc untrimmed.fastq -o ./tmp # analyse les données et output dans tmp
mv ./tmp/untrimmed_fastqc.html ../analysis/ # déplace dans le dossier résultat.
